export type ProductStatus = 'approved' | 'pending' | 'rejected';

export type Product = {
  id: string;
  name: string;
  category: string;
  type?: 'product' | 'service';
  price: number;
  originalPrice: number;
  unit: string;
  icon: string;
  bg: string;
  tag?: string;
  tagColor?: string;
  rating: number;
  reviews: number;
  sold: number;
  desc: string;
  specs: string[];
  origin: string;
  certifications: string[];
  imageUrl?: string;
  // Seller fields — only present on business-uploaded products
  sellerId?: string;
  sellerName?: string;
  status?: ProductStatus;
  submittedAt?: string;
  rejectionReason?: string;
};

export type CategoryType = 'all' | 'service' | 'product';

export type Category = {
  id: string;
  label: string;
  icon: string;
  type: CategoryType;
};

export const categories: Category[] = [
  { id: 'tat-ca', label: 'Tất cả', icon: '🛒', type: 'all' },
  // Dịch vụ
  { id: 'tu-van', label: 'Tư vấn nông nghiệp', icon: '📋', type: 'service' },
  {
    id: 'phan-tich',
    label: 'Phân tích – kiểm nghiệm',
    icon: '🔬',
    type: 'service',
  },
  {
    id: 'dao-tao',
    label: 'Đào tạo – chuyển giao CN',
    icon: '🎓',
    type: 'service',
  },
  // Sản phẩm
  {
    id: 'giong-cay-trong',
    label: 'Giống cây trồng',
    icon: '🌾',
    type: 'product',
  },
  {
    id: 'giong-vat-nuoi',
    label: 'Giống vật nuôi – thủy sản',
    icon: '🐄',
    type: 'product',
  },
  {
    id: 'san-pham-vien',
    label: 'Sản phẩm Viện Nông Nghiệp',
    icon: '🌿',
    type: 'product',
  },
  { id: 'vat-tu', label: 'Vật tư – chế phẩm', icon: '🧪', type: 'product' },
];

export const products: Product[] = [
  // ─── DỊCH VỤ ──────────────────────────────────────────────────────────────

  {
    id: 'tv-quy-hoach',
    name: 'Tư vấn quy hoạch phát triển nông nghiệp',
    category: 'tu-van',
    type: 'service',
    price: 0,
    originalPrice: 0,
    unit: 'dự án',
    icon: '📋',
    bg: 'bg-blue-50',
    tag: 'Dịch vụ',
    tagColor: 'bg-blue-600 text-white',
    rating: 4.9,
    reviews: 58,
    sold: 134,
    origin: 'Viện Nông Nghiệp Thanh Hóa',
    certifications: ['Tư vấn được cấp phép', 'Bộ NN&PTNT'],
    desc: 'Tư vấn quy hoạch phát triển sản xuất nông nghiệp; lập đề án, dự án, phương án, mô hình phát triển nông nghiệp; định hướng phát triển vùng sản xuất.',
    specs: [
      'Lập đề án, dự án nông nghiệp',
      'Xây dựng phương án sản xuất',
      'Định hướng vùng chuyên canh',
      'Tư vấn mô hình nông nghiệp',
    ],
  },
  {
    id: 'tv-thi-truong',
    name: 'Tư vấn thị trường & chuỗi giá trị',
    category: 'tu-van',
    type: 'service',
    price: 0,
    originalPrice: 0,
    unit: 'hợp đồng',
    icon: '📊',
    bg: 'bg-indigo-50',
    tag: 'Dịch vụ',
    tagColor: 'bg-indigo-600 text-white',
    rating: 4.8,
    reviews: 32,
    sold: 87,
    origin: 'Viện Nông Nghiệp Thanh Hóa',
    certifications: ['Tư vấn kinh tế NN', 'Chuyên gia thị trường'],
    desc: 'Tư vấn thị trường, chuỗi giá trị nông sản; xúc tiến thương mại; kết nối tiêu thụ sản phẩm; định hướng phát triển thương hiệu nông sản.',
    specs: [
      'Phân tích chuỗi giá trị',
      'Xúc tiến thương mại',
      'Kết nối thị trường tiêu thụ',
      'Phát triển thương hiệu nông sản',
    ],
  },
  {
    id: 'pt-dat-nuoc',
    name: 'Phân tích đất, nước, phân bón',
    category: 'phan-tich',
    type: 'service',
    price: 0,
    originalPrice: 0,
    unit: 'mẫu',
    icon: '🔬',
    bg: 'bg-teal-50',
    tag: 'Dịch vụ',
    tagColor: 'bg-teal-600 text-white',
    rating: 4.9,
    reviews: 142,
    sold: 890,
    origin: 'Phòng thí nghiệm Viện Nông Nghiệp TH',
    certifications: ['ISO/IEC 17025', 'Bộ KH&CN công nhận'],
    desc: 'Phân tích mẫu đất nông nghiệp, nước tưới, phân bón; dư lượng thuốc bảo vệ thực vật; đánh giá chất lượng môi trường canh tác, đề xuất cải tạo.',
    specs: [
      'Phân tích lý – hóa – sinh học đất',
      'Kiểm tra chất lượng nước tưới',
      'Phân tích thành phần phân bón',
      'Dư lượng thuốc BVTV',
    ],
  },
  {
    id: 'pt-giong',
    name: 'Kiểm nghiệm giống cây trồng & vật nuôi',
    category: 'phan-tich',
    type: 'service',
    price: 0,
    originalPrice: 0,
    unit: 'mẫu',
    icon: '🧬',
    bg: 'bg-purple-50',
    tag: 'Dịch vụ',
    tagColor: 'bg-purple-600 text-white',
    rating: 4.8,
    reviews: 76,
    sold: 410,
    origin: 'Phòng thí nghiệm Viện Nông Nghiệp TH',
    certifications: ['ISO/IEC 17025', 'Kiểm định nhà nước'],
    desc: 'Kiểm nghiệm chất lượng giống cây trồng, vật nuôi, thức ăn chăn nuôi; kiểm tra mẫu bệnh cây trồng, vật nuôi, thủy sản; môi trường chăn nuôi.',
    specs: [
      'Kiểm định chất lượng hạt giống',
      'Kiểm tra bệnh cây trồng',
      'Kiểm nghiệm thức ăn chăn nuôi',
      'Kiểm tra môi trường chăn nuôi',
    ],
  },
  {
    id: 'dt-ky-thuat',
    name: 'Tập huấn kỹ thuật sản xuất nông nghiệp',
    category: 'dao-tao',
    type: 'service',
    price: 0,
    originalPrice: 0,
    unit: 'khóa',
    icon: '🎓',
    bg: 'bg-amber-50',
    tag: 'Dịch vụ',
    tagColor: 'bg-amber-600 text-white',
    rating: 4.9,
    reviews: 215,
    sold: 560,
    origin: 'Viện Nông Nghiệp Thanh Hóa',
    certifications: ['Giấy phép đào tạo', 'Bộ NN&PTNT'],
    desc: 'Tập huấn kỹ thuật canh tác lúa, rau màu, cây ăn quả; đào tạo quy trình chăn nuôi, nuôi trồng thủy sản; ứng dụng nông nghiệp hữu cơ, an toàn sinh học.',
    specs: [
      'Kỹ thuật canh tác lúa, rau, cây ăn quả',
      'Quy trình chăn nuôi & thủy sản',
      'Nông nghiệp hữu cơ & an toàn',
      'Cấp chứng chỉ sau khóa học',
    ],
  },
  {
    id: 'dt-cong-nghe-cao',
    name: 'Chuyển giao công nghệ nông nghiệp cao',
    category: 'dao-tao',
    type: 'service',
    price: 0,
    originalPrice: 0,
    unit: 'hợp đồng',
    icon: '🤝',
    bg: 'bg-green-50',
    tag: 'Dịch vụ',
    tagColor: 'bg-green-600 text-white',
    rating: 4.8,
    reviews: 48,
    sold: 112,
    origin: 'Viện Nông Nghiệp Thanh Hóa',
    certifications: ['Chuyển giao KH&CN', 'Bộ KH&CN'],
    desc: 'Chuyển giao giống mới, công nghệ mới, mô hình nông nghiệp công nghệ cao, hữu cơ, tuần hoàn; triển khai tại địa phương với hỗ trợ kỹ thuật trực tiếp.',
    specs: [
      'Chuyển giao giống mới xác nhận',
      'Mô hình nông nghiệp công nghệ cao',
      'Nông nghiệp tuần hoàn & hữu cơ',
      'Hỗ trợ kỹ thuật tại chỗ',
    ],
  },

  // ─── GIỐNG CÂY TRỒNG ──────────────────────────────────────────────────────

  {
    id: 'lua-bc15',
    name: 'Lúa giống BC15',
    category: 'giong-cay-trong',
    price: 45000,
    originalPrice: 52000,
    unit: 'kg',
    icon: '🌾',
    bg: 'bg-amber-50',
    tag: 'Bán chạy',
    tagColor: 'bg-red-500 text-white',
    rating: 4.8,
    reviews: 312,
    sold: 1540,
    origin: 'Viện Nông Nghiệp Thanh Hóa',
    certifications: ['Giống xác nhận', 'Bộ NN&PTNT'],
    desc: 'Giống lúa thuần chất lượng cao, phù hợp điều kiện đất đai và khí hậu Thanh Hóa. Cho năng suất ổn định, gạo trắng trong, cơm dẻo thơm.',
    specs: [
      'Năng suất: 65–70 tạ/ha',
      'TGST: 125–130 ngày',
      'Chất lượng gạo ngon',
      'Kháng đạo ôn tốt',
    ],
  },
  {
    id: 'lua-th33',
    name: 'Lúa TH3-3',
    category: 'giong-cay-trong',
    price: 55000,
    originalPrice: 65000,
    unit: 'kg',
    icon: '🌾',
    bg: 'bg-amber-50',
    tag: 'Chất lượng cao',
    tagColor: 'bg-amber-500 text-white',
    rating: 4.9,
    reviews: 198,
    sold: 870,
    origin: 'Viện Nông Nghiệp Thanh Hóa',
    certifications: ['Giống xác nhận', 'Xuất khẩu'],
    desc: 'Giống lúa lai 2 dòng, tiềm năng năng suất cao, chất lượng gạo xuất khẩu. Thích hợp vụ xuân và vụ mùa sớm.',
    specs: [
      'Năng suất: 70–75 tạ/ha',
      'TGST: 120–125 ngày',
      'Gạo thơm, chất lượng xuất khẩu',
      'Chịu rét tốt',
    ],
  },
  {
    id: 'lua-man',
    name: 'Lúa chịu mặn TH-M1',
    category: 'giong-cay-trong',
    price: 60000,
    originalPrice: 60000,
    unit: 'kg',
    icon: '🌾',
    bg: 'bg-green-50',
    tag: 'Độc quyền',
    tagColor: 'bg-green-600 text-white',
    rating: 4.7,
    reviews: 89,
    sold: 340,
    origin: 'Viện Nông Nghiệp Thanh Hóa',
    certifications: ['Nghiên cứu độc quyền', 'Chứng nhận mới'],
    desc: 'Giống lúa chịu mặn do Viện nghiên cứu và chọn tạo, phù hợp vùng đất nhiễm mặn ven biển Thanh Hóa.',
    specs: [
      'Chịu mặn đến 4‰',
      'Năng suất: 55–60 tạ/ha',
      'Thích hợp vùng ven biển',
      'TGST: 115–120 ngày',
    ],
  },
  {
    id: 'ngo-dk9901',
    name: 'Ngô giống DK9901',
    category: 'giong-cay-trong',
    price: 180000,
    originalPrice: 210000,
    unit: 'kg',
    icon: '🌽',
    bg: 'bg-yellow-50',
    tag: 'Phổ biến',
    tagColor: 'bg-yellow-500 text-white',
    rating: 4.6,
    reviews: 145,
    sold: 620,
    origin: 'ThaiBinh Seed (phân phối độc quyền)',
    certifications: ['Ngô lai F1', 'Giống xác nhận'],
    desc: 'Ngô lai F1 đơn chéo, thích ứng rộng với nhiều vùng sinh thái. Thân cứng, chịu đổ ngã, hạt to đều.',
    specs: [
      'Năng suất: 8–10 tấn/ha',
      'Chịu hạn tốt',
      'Thích nghi rộng',
      'TGST: 100–105 ngày',
    ],
  },
  {
    id: 'keo-mo',
    name: 'Keo tai tượng giống mô',
    category: 'giong-cay-trong',
    price: 3500,
    originalPrice: 4200,
    unit: 'cây',
    icon: '🌲',
    bg: 'bg-green-50',
    tag: 'Sạch bệnh',
    tagColor: 'bg-green-700 text-white',
    rating: 4.7,
    reviews: 96,
    sold: 45000,
    origin: 'Viện Nông Nghiệp Thanh Hóa',
    certifications: ['Giống lâm nghiệp', 'Nhân giống vô tính'],
    desc: 'Keo tai tượng nhân giống bằng công nghệ nuôi cấy mô, cây giống đồng đều, sạch bệnh, tỷ lệ sống cao. Phù hợp trồng rừng kinh tế.',
    specs: [
      'Nhân giống bằng nuôi cấy mô',
      'Tỷ lệ sống > 95%',
      'Cây đồng đều, sạch bệnh',
      'Thích hợp đất đồi núi Thanh Hóa',
    ],
  },
  {
    id: 'dua-md2',
    name: 'Dứa MD2 giống mô',
    category: 'giong-cay-trong',
    price: 8000,
    originalPrice: 9500,
    unit: 'cây',
    icon: '🍍',
    bg: 'bg-yellow-50',
    tag: 'Xuất khẩu',
    tagColor: 'bg-yellow-600 text-white',
    rating: 4.8,
    reviews: 64,
    sold: 12000,
    origin: 'Viện Nông Nghiệp Thanh Hóa',
    certifications: ['Giống công nghệ cao', 'Xuất khẩu'],
    desc: 'Giống dứa MD2 nhân bằng công nghệ nuôi cấy mô, chất lượng quả cao, vỏ vàng đẹp, ngọt, thơm, phù hợp xuất khẩu và chế biến.',
    specs: [
      'Nhân bằng nuôi cấy mô',
      'Trọng lượng quả 1.5–2.5 kg',
      'Vỏ vàng, ruột vàng, ngọt thơm',
      'Năng suất 40–50 tấn/ha',
    ],
  },

  // ─── GIỐNG VẬT NUÔI – THỦY SẢN ───────────────────────────────────────────

  {
    id: 'ga-giong-lac-thuy',
    name: 'Gà giống Lạc Thủy F1',
    category: 'giong-vat-nuoi',
    price: 28000,
    originalPrice: 32000,
    unit: 'con',
    icon: '🐔',
    bg: 'bg-orange-50',
    tag: 'Chất lượng cao',
    tagColor: 'bg-orange-500 text-white',
    rating: 4.7,
    reviews: 88,
    sold: 3200,
    origin: 'Trại giống gia cầm Viện Nông Nghiệp TH',
    certifications: ['Giống gia cầm quốc gia', 'An toàn dịch bệnh'],
    desc: 'Gà giống Lạc Thủy F1 chất lượng cao, được chọn lọc và kiểm tra dịch bệnh. Phù hợp chăn nuôi quy mô hộ gia đình và trang trại.',
    specs: [
      'Khối lượng xuất bán: 2–2.5 kg/con',
      'Tỷ lệ nuôi sống > 95%',
      'Đã tiêm vaccine đầy đủ',
      'Phù hợp nuôi thả vườn và công nghiệp',
    ],
  },
  {
    id: 'lon-giong',
    name: 'Lợn giống Yorkshire × Landrace',
    category: 'giong-vat-nuoi',
    price: 3200000,
    originalPrice: 3800000,
    unit: 'con',
    icon: '🐷',
    bg: 'bg-pink-50',
    tag: 'Năng suất cao',
    tagColor: 'bg-pink-600 text-white',
    rating: 4.8,
    reviews: 52,
    sold: 480,
    origin: 'Trại giống lợn Viện Nông Nghiệp TH',
    certifications: ['Giống lợn quốc gia', 'An toàn dịch bệnh'],
    desc: 'Lợn giống lai F1 Yorkshire × Landrace, tăng trọng nhanh, tỷ lệ thịt nạc cao. Phù hợp nuôi công nghiệp và bán công nghiệp.',
    specs: [
      'Tăng trọng 700–800g/ngày',
      'Tỷ lệ thịt nạc ≥ 55%',
      'Đã tiêm phòng đầy đủ',
      'Trọng lượng xuất chuồng: 110–120 kg',
    ],
  },
  {
    id: 'ca-tram-co',
    name: 'Giống cá Trắm cỏ',
    category: 'giong-vat-nuoi',
    price: 18000,
    originalPrice: 22000,
    unit: 'kg',
    icon: '🐟',
    bg: 'bg-cyan-50',
    tag: 'Phổ biến',
    tagColor: 'bg-cyan-600 text-white',
    rating: 4.6,
    reviews: 76,
    sold: 8500,
    origin: 'Trại cá giống Viện Nông Nghiệp TH',
    certifications: ['Giống thủy sản quốc gia', 'Sạch bệnh'],
    desc: 'Giống cá Trắm cỏ chất lượng cao, được sản xuất từ đàn bố mẹ tuyển chọn. Tăng trưởng nhanh, thích nghi tốt với điều kiện ao nuôi Thanh Hóa.',
    specs: [
      'Cỡ giống: 8–12 cm/con',
      'Tỷ lệ sống > 90%',
      'Sạch ký sinh trùng',
      'Tăng trọng 1–1.5 kg/tháng',
    ],
  },
  {
    id: 'tom-giong',
    name: 'Tôm thẻ chân trắng giống',
    category: 'giong-vat-nuoi',
    price: 120,
    originalPrice: 150,
    unit: 'con (Post 12)',
    icon: '🦐',
    bg: 'bg-blue-50',
    tag: 'SPF sạch bệnh',
    tagColor: 'bg-blue-600 text-white',
    rating: 4.7,
    reviews: 61,
    sold: 520000,
    origin: 'Trại giống thủy sản Viện Nông Nghiệp TH',
    certifications: ['SPF sạch bệnh', 'Kiểm dịch nhà nước'],
    desc: 'Tôm thẻ chân trắng giống Post 12, sạch bệnh SPF, khỏe mạnh, đồng đều. Phù hợp nuôi ao đất và ao bạt tại vùng ven biển Thanh Hóa.',
    specs: [
      'Giai đoạn Post 12',
      'Tỷ lệ sống > 85%',
      'SPF – sạch 10 loại bệnh',
      'Chiều dài > 1.2 cm',
    ],
  },

  // ─── SẢN PHẨM VIỆN NÔNG NGHIỆP ───────────────────────────────────────────

  {
    id: 'rau-sach',
    name: 'Rau cải xanh VietGAP',
    category: 'san-pham-vien',
    price: 15000,
    originalPrice: 18000,
    unit: 'kg',
    icon: '🥬',
    bg: 'bg-lime-50',
    tag: 'VietGAP',
    tagColor: 'bg-lime-600 text-white',
    rating: 4.8,
    reviews: 156,
    sold: 780,
    origin: 'Vùng RAT Viện Nông Nghiệp TH',
    certifications: ['VietGAP', 'Không dư lượng thuốc'],
    desc: 'Rau cải xanh, cải ngọt trồng theo tiêu chuẩn VietGAP. Tươi sạch, không tồn dư thuốc BVTV.',
    specs: [
      'Chứng nhận VietGAP',
      'Không dư lượng thuốc',
      'Tươi – Đặt trước 1 ngày',
      'Giao hàng Tp. Thanh Hóa',
    ],
  },
  {
    id: 'cam-duong',
    name: 'Cam Đường Canh Ngọc Lặc',
    category: 'san-pham-vien',
    price: 35000,
    originalPrice: 42000,
    unit: 'kg',
    icon: '🍊',
    bg: 'bg-orange-50',
    tag: 'Đặc sản',
    tagColor: 'bg-orange-500 text-white',
    rating: 4.9,
    reviews: 423,
    sold: 2300,
    origin: 'Vườn cam Ngọc Lặc, Thanh Hóa',
    certifications: ['Đặc sản địa phương', 'Không thuốc tăng trưởng'],
    desc: 'Cam Đường Canh trồng tại vùng đồi núi Ngọc Lặc, thu hoạch tự nhiên. Vỏ mỏng, múi mọng, vị ngọt thanh.',
    specs: [
      'Vườn sản xuất Ngọc Lặc',
      'Không thuốc tăng trưởng',
      'Thu hoạch tháng 11–1',
      'Ngọt, ít hạt, thơm',
    ],
  },
  {
    id: 'gao-st25',
    name: 'Gạo ST25 Thanh Hóa',
    category: 'san-pham-vien',
    price: 28000,
    originalPrice: 32000,
    unit: 'kg',
    icon: '🍚',
    bg: 'bg-yellow-50',
    tag: 'Ngon nhất',
    tagColor: 'bg-yellow-600 text-white',
    rating: 5.0,
    reviews: 612,
    sold: 4500,
    origin: 'Cánh đồng lúa Yên Định',
    certifications: ['Gạo ngon thế giới', 'An toàn thực phẩm'],
    desc: 'Gạo ST25 được trồng tại vùng đồng bằng Yên Định, cơm trắng thơm, dẻo mềm vừa phải.',
    specs: [
      'Cơm thơm, dẻo mềm',
      'Hạt dài đều',
      'Không chất bảo quản',
      'Đóng gói chân không',
    ],
  },
  {
    id: 'mat-ong-rung',
    name: 'Mật ong rừng Thường Xuân',
    category: 'san-pham-vien',
    price: 180000,
    originalPrice: 220000,
    unit: 'lít',
    icon: '🍯',
    bg: 'bg-amber-50',
    tag: 'Tự nhiên',
    tagColor: 'bg-amber-600 text-white',
    rating: 4.9,
    reviews: 287,
    sold: 890,
    origin: 'Rừng nguyên sinh Thường Xuân',
    certifications: ['100% tự nhiên', 'Kiểm định chất lượng'],
    desc: 'Mật ong rừng nguyên chất từ rừng nguyên sinh Thường Xuân, không pha trộn, giàu dưỡng chất.',
    specs: [
      '100% tự nhiên',
      'Độ ẩm < 20%',
      'Không chất phụ gia',
      'Hạn sử dụng 2 năm',
    ],
  },
  {
    id: 'ca-kho-to',
    name: 'Cá kho tộ đặc sản Thanh Hóa',
    category: 'san-pham-vien',
    price: 120000,
    originalPrice: 150000,
    unit: 'hộp 500g',
    icon: '🐟',
    bg: 'bg-red-50',
    tag: 'Đặc sản',
    tagColor: 'bg-red-500 text-white',
    rating: 4.7,
    reviews: 198,
    sold: 650,
    origin: 'Làng nghề Hoằng Hóa',
    certifications: ['VSATTP', 'Truyền thống'],
    desc: 'Cá kho tộ theo công thức gia truyền làng nghề Hoằng Hóa, đậm đà hương vị, tiện dụng ăn liền.',
    specs: [
      'Nguyên liệu tươi sống',
      'Gia vị truyền thống',
      'Hộp kín chân không',
      'Hạn dùng 3 tháng',
    ],
  },

  // ─── VẬT TƯ – CHẾ PHẨM NÔNG NGHIỆP ──────────────────────────────────────

  {
    id: 'phan-huu-co',
    name: 'Phân hữu cơ vi sinh HUMIC',
    category: 'vat-tu',
    price: 8500,
    originalPrice: 10000,
    unit: 'kg',
    icon: '🌱',
    bg: 'bg-emerald-50',
    tag: 'Hữu cơ',
    tagColor: 'bg-emerald-600 text-white',
    rating: 4.7,
    reviews: 267,
    sold: 2100,
    origin: 'Viện Nông Nghiệp Thanh Hóa',
    certifications: ['Hữu cơ VN', 'ISO 9001'],
    desc: 'Phân hữu cơ vi sinh cao cấp từ phụ phẩm nông nghiệp lên men sinh học. Cải thiện kết cấu đất, tăng giữ nước.',
    specs: [
      'Hữu cơ ≥ 15%',
      'Vi sinh ≥ 1×10⁶ CFU/g',
      'pH 6.5–7.5',
      'Không kim loại nặng',
    ],
  },
  {
    id: 'phan-npk',
    name: 'Phân NPK 16-16-8',
    category: 'vat-tu',
    price: 12000,
    originalPrice: 14000,
    unit: 'kg',
    icon: '🌱',
    bg: 'bg-blue-50',
    tag: 'Đa dụng',
    tagColor: 'bg-blue-500 text-white',
    rating: 4.5,
    reviews: 183,
    sold: 1820,
    origin: 'Nhà máy phân bón Văn Điển',
    certifications: ['TCVN 9301:2012', 'Chứng nhận CL'],
    desc: 'Phân NPK cân đối, cung cấp đủ 3 dưỡng chất thiết yếu cho cây trồng. Thích hợp bón lót và bón thúc.',
    specs: [
      'N: 16%, P₂O₅: 16%, K₂O: 8%',
      'Dạng hạt, tan nhanh',
      'Phù hợp lúa, ngô, rau',
      'Chứng nhận chất lượng',
    ],
  },
  {
    id: 'thuoc-sinh-hoc',
    name: 'Thuốc trừ sâu sinh học BT',
    category: 'vat-tu',
    price: 95000,
    originalPrice: 110000,
    unit: 'lít',
    icon: '🍃',
    bg: 'bg-teal-50',
    tag: 'An toàn',
    tagColor: 'bg-teal-600 text-white',
    rating: 4.6,
    reviews: 94,
    sold: 430,
    origin: 'Công ty BVTV An Giang',
    certifications: ['Sinh học', 'An toàn thực phẩm'],
    desc: 'Thuốc trừ sâu sinh học từ vi khuẩn Bacillus thuringiensis, an toàn cho thiên địch và hệ sinh thái.',
    specs: [
      'Gốc vi khuẩn BT',
      'Không độc với người',
      'PHI: 3 ngày',
      'Không gây nhờn thuốc',
    ],
  },
  {
    id: 'che-pham-vi-sinh',
    name: 'Chế phẩm vi sinh Trichoderma',
    category: 'vat-tu',
    price: 45000,
    originalPrice: 55000,
    unit: 'kg',
    icon: '🧫',
    bg: 'bg-green-50',
    tag: 'Sinh học',
    tagColor: 'bg-green-600 text-white',
    rating: 4.7,
    reviews: 112,
    sold: 760,
    origin: 'Viện Nông Nghiệp Thanh Hóa',
    certifications: ['Chế phẩm sinh học', 'Bộ NN&PTNT'],
    desc: 'Chế phẩm vi sinh Trichoderma phòng trừ bệnh nấm đất, cải thiện hệ vi sinh đất, tăng khả năng hấp thu dinh dưỡng của cây trồng.',
    specs: [
      'Mật độ nấm ≥ 10⁸ CFU/g',
      'Phòng trừ nấm Fusarium, Pythium',
      'An toàn với người và môi trường',
      'Dùng cho lúa, rau, cây ăn quả',
    ],
  },
];

export const banners = [
  {
    id: 1,
    title: 'Lúa giống',
    subtitle: 'Nghiên cứu, tuyển chọn và nhân giống độc quyền',
    desc: 'Các giống lúa thảo dược phù hợp với điều kiện thổ nhưỡng Thanh Hóa – năng suất ổn định, chất lượng gạo vượt trội.',
    cta: 'Xem giống lúa',
    href: '/san-pham?category=giong-cay-trong',
    bg: 'from-green-900 to-green-600',
    badge: 'GIỐNG LÚA THẢO DƯỢC',
  },
  {
    id: 2,
    title: 'Nấm dược liệu',
    subtitle: 'Công nghệ nuôi cấy hiện đại, dược tính cao',
    desc: 'Quy trình kiểm soát nhiệt độ, độ ẩm và ánh sáng chuẩn quốc tế trong các phòng nuôi được trang bị hiện đại.',
    cta: 'Tìm hiểu thêm',
    href: '/san-pham?category=san-pham-vien',
    bg: 'from-purple-900 to-purple-700',
    badge: 'NẤM DƯỢC LIỆU – ĐỘC QUYỀN',
  },
  {
    id: 3,
    title: 'Sản phẩm từ Đông trùng hạ thảo',
    subtitle: 'Nấm khô, rượu ngâm – đặc sản Thanh Hóa',
    desc: 'Chế biến từ nấm Đông trùng hạ thảo tự nhiên – bảo quản lâu dài, giữ nguyên dưỡng chất quý hiếm.',
    cta: 'Xem sản phẩm',
    href: '/san-pham?category=san-pham-vien',
    bg: 'from-amber-800 to-amber-600',
    badge: 'CHẾ BIẾN ĐẶC SẢN',
  },
];

export function formatPrice(price: number): string {
  return price.toLocaleString('vi-VN') + 'đ';
}

export function discountPercent(original: number, current: number): number {
  return Math.round(((original - current) / original) * 100);
}
