export type ProductStatus = "approved" | "pending" | "rejected";

export type Product = {
  id: string;
  name: string;
  category: string;
  price: number;
  originalPrice: number;
  unit: string;
  icon: string;
  bg: string;
  tag?: string;
  tagColor?: string;
  rating: number;
  reviews: number;
  sold: number;
  desc: string;
  specs: string[];
  origin: string;
  certifications: string[];
  // Seller fields — only present on business-uploaded products
  sellerId?: string;
  sellerName?: string;
  status?: ProductStatus;
  submittedAt?: string;
  rejectionReason?: string;
};

export const categories = [
  { id: "tat-ca", label: "Tất cả sản phẩm", icon: "🛒" },
  { id: "giong", label: "Giống cây trồng", icon: "🌾" },
  { id: "phanbon", label: "Phân bón", icon: "🌱" },
  { id: "thuoc", label: "Thuốc BVTV", icon: "🍃" },
  { id: "rau", label: "Rau & Cây ăn quả", icon: "🥬" },
  { id: "thucpham", label: "Thực phẩm đặc sản", icon: "🍚" },
];

export const products: Product[] = [
  {
    id: "lua-bc15",
    name: "Lúa giống BC15",
    category: "giong",
    price: 45000,
    originalPrice: 52000,
    unit: "kg",
    icon: "🌾",
    bg: "bg-amber-50",
    tag: "Bán chạy",
    tagColor: "bg-red-500 text-white",
    rating: 4.8,
    reviews: 312,
    sold: 1540,
    origin: "Viện Nông Nghiệp Thanh Hóa",
    certifications: ["Giống xác nhận", "Bộ NN&PTNT"],
    desc: "Giống lúa thuần chất lượng cao, phù hợp điều kiện đất đai và khí hậu Thanh Hóa. Cho năng suất ổn định, gạo trắng trong, cơm dẻo thơm.",
    specs: ["Năng suất: 65–70 tạ/ha", "TGST: 125–130 ngày", "Chất lượng gạo ngon", "Kháng đạo ôn tốt"],
  },
  {
    id: "lua-th33",
    name: "Lúa TH3-3",
    category: "giong",
    price: 55000,
    originalPrice: 65000,
    unit: "kg",
    icon: "🌾",
    bg: "bg-amber-50",
    tag: "Chất lượng cao",
    tagColor: "bg-amber-500 text-white",
    rating: 4.9,
    reviews: 198,
    sold: 870,
    origin: "Viện Nông Nghiệp Thanh Hóa",
    certifications: ["Giống xác nhận", "Xuất khẩu"],
    desc: "Giống lúa lai 2 dòng, tiềm năng năng suất cao, chất lượng gạo xuất khẩu. Thích hợp vụ xuân và vụ mùa sớm.",
    specs: ["Năng suất: 70–75 tạ/ha", "TGST: 120–125 ngày", "Gạo thơm, chất lượng xuất khẩu", "Chịu rét tốt"],
  },
  {
    id: "lua-man",
    name: "Lúa chịu mặn TH-M1",
    category: "giong",
    price: 60000,
    originalPrice: 60000,
    unit: "kg",
    icon: "🌾",
    bg: "bg-green-50",
    tag: "Độc quyền",
    tagColor: "bg-green-600 text-white",
    rating: 4.7,
    reviews: 89,
    sold: 340,
    origin: "Viện Nông Nghiệp Thanh Hóa",
    certifications: ["Nghiên cứu độc quyền", "Chứng nhận mới"],
    desc: "Giống lúa chịu mặn do Viện nghiên cứu và chọn tạo, phù hợp vùng đất nhiễm mặn ven biển Thanh Hóa.",
    specs: ["Chịu mặn đến 4‰", "Năng suất: 55–60 tạ/ha", "Thích hợp vùng ven biển", "TGST: 115–120 ngày"],
  },
  {
    id: "ngo-dk9901",
    name: "Ngô giống DK9901",
    category: "giong",
    price: 180000,
    originalPrice: 210000,
    unit: "kg",
    icon: "🌽",
    bg: "bg-yellow-50",
    tag: "Phổ biến",
    tagColor: "bg-yellow-500 text-white",
    rating: 4.6,
    reviews: 145,
    sold: 620,
    origin: "ThaiBinh Seed (phân phối độc quyền)",
    certifications: ["Ngô lai F1", "Giống xác nhận"],
    desc: "Ngô lai F1 đơn chéo, thích ứng rộng với nhiều vùng sinh thái. Thân cứng, chịu đổ ngã, hạt to đều.",
    specs: ["Năng suất: 8–10 tấn/ha", "Chịu hạn tốt", "Thích nghi rộng", "TGST: 100–105 ngày"],
  },
  {
    id: "phan-huu-co",
    name: "Phân hữu cơ vi sinh HUMIC",
    category: "phanbon",
    price: 8500,
    originalPrice: 10000,
    unit: "kg",
    icon: "🌱",
    bg: "bg-emerald-50",
    tag: "Hữu cơ",
    tagColor: "bg-emerald-600 text-white",
    rating: 4.7,
    reviews: 267,
    sold: 2100,
    origin: "Viện Nông Nghiệp Thanh Hóa",
    certifications: ["Hữu cơ VN", "ISO 9001"],
    desc: "Phân hữu cơ vi sinh cao cấp từ phụ phẩm nông nghiệp lên men sinh học. Cải thiện kết cấu đất, tăng giữ nước.",
    specs: ["Hữu cơ ≥ 15%", "Vi sinh ≥ 1×10⁶ CFU/g", "pH 6.5–7.5", "Không kim loại nặng"],
  },
  {
    id: "phan-npk",
    name: "Phân NPK 16-16-8",
    category: "phanbon",
    price: 12000,
    originalPrice: 14000,
    unit: "kg",
    icon: "🌱",
    bg: "bg-blue-50",
    tag: "Đa dụng",
    tagColor: "bg-blue-500 text-white",
    rating: 4.5,
    reviews: 183,
    sold: 1820,
    origin: "Nhà máy phân bón Văn Điển",
    certifications: ["TCVN 9301:2012", "Chứng nhận CL"],
    desc: "Phân NPK cân đối, cung cấp đủ 3 dưỡng chất thiết yếu cho cây trồng. Thích hợp bón lót và bón thúc.",
    specs: ["N: 16%, P₂O₅: 16%, K₂O: 8%", "Dạng hạt, tan nhanh", "Phù hợp lúa, ngô, rau", "Chứng nhận chất lượng"],
  },
  {
    id: "thuoc-sinh-hoc",
    name: "Thuốc trừ sâu sinh học BT",
    category: "thuoc",
    price: 95000,
    originalPrice: 110000,
    unit: "lít",
    icon: "🍃",
    bg: "bg-teal-50",
    tag: "An toàn",
    tagColor: "bg-teal-600 text-white",
    rating: 4.6,
    reviews: 94,
    sold: 430,
    origin: "Công ty BVTV An Giang",
    certifications: ["Sinh học", "An toàn thực phẩm"],
    desc: "Thuốc trừ sâu sinh học từ vi khuẩn Bacillus thuringiensis, an toàn cho thiên địch và hệ sinh thái.",
    specs: ["Gốc vi khuẩn BT", "Không độc với người", "PHI: 3 ngày", "Không gây nhờn thuốc"],
  },
  {
    id: "rau-sach",
    name: "Rau cải xanh VietGAP",
    category: "rau",
    price: 15000,
    originalPrice: 18000,
    unit: "kg",
    icon: "🥬",
    bg: "bg-lime-50",
    tag: "VietGAP",
    tagColor: "bg-lime-600 text-white",
    rating: 4.8,
    reviews: 156,
    sold: 780,
    origin: "Vùng RAT Viện Nông Nghiệp TH",
    certifications: ["VietGAP", "Không dư lượng thuốc"],
    desc: "Rau cải xanh, cải ngọt trồng theo tiêu chuẩn VietGAP. Tươi sạch, không tồn dư thuốc BVTV.",
    specs: ["Chứng nhận VietGAP", "Không dư lượng thuốc", "Tươi – Đặt trước 1 ngày", "Giao hàng Tp. Thanh Hóa"],
  },
  {
    id: "cam-duong",
    name: "Cam Đường Canh Ngọc Lặc",
    category: "rau",
    price: 35000,
    originalPrice: 42000,
    unit: "kg",
    icon: "🍊",
    bg: "bg-orange-50",
    tag: "Đặc sản",
    tagColor: "bg-orange-500 text-white",
    rating: 4.9,
    reviews: 423,
    sold: 2300,
    origin: "Vườn cam Ngọc Lặc, Thanh Hóa",
    certifications: ["Đặc sản địa phương", "Không thuốc tăng trưởng"],
    desc: "Cam Đường Canh trồng tại vùng đồi núi Ngọc Lặc, thu hoạch tự nhiên. Vỏ mỏng, múi mọng, vị ngọt thanh.",
    specs: ["Vườn sản xuất Ngọc Lặc", "Không thuốc tăng trưởng", "Thu hoạch tháng 11–1", "Ngọt, ít hạt, thơm"],
  },
  {
    id: "gao-st25",
    name: "Gạo ST25 Thanh Hóa",
    category: "thucpham",
    price: 28000,
    originalPrice: 32000,
    unit: "kg",
    icon: "🍚",
    bg: "bg-yellow-50",
    tag: "Ngon nhất",
    tagColor: "bg-yellow-600 text-white",
    rating: 5.0,
    reviews: 612,
    sold: 4500,
    origin: "Cánh đồng lúa Yên Định",
    certifications: ["Gạo ngon thế giới", "An toàn thực phẩm"],
    desc: "Gạo ST25 được trồng tại vùng đồng bằng Yên Định, cơm trắng thơm, dẻo mềm vừa phải.",
    specs: ["Cơm thơm, dẻo mềm", "Hạt dài đều", "Không chất bảo quản", "Đóng gói chân không"],
  },
  {
    id: "mat-ong-rung",
    name: "Mật ong rừng Thường Xuân",
    category: "thucpham",
    price: 180000,
    originalPrice: 220000,
    unit: "lít",
    icon: "🍯",
    bg: "bg-amber-50",
    tag: "Tự nhiên",
    tagColor: "bg-amber-600 text-white",
    rating: 4.9,
    reviews: 287,
    sold: 890,
    origin: "Rừng nguyên sinh Thường Xuân",
    certifications: ["100% tự nhiên", "Kiểm định chất lượng"],
    desc: "Mật ong rừng nguyên chất từ rừng nguyên sinh Thường Xuân, không pha trộn, giàu dưỡng chất.",
    specs: ["100% tự nhiên", "Độ ẩm < 20%", "Không chất phụ gia", "Hạn sử dụng 2 năm"],
  },
  {
    id: "ca-kho-to",
    name: "Cá kho tộ đặc sản Thanh Hóa",
    category: "thucpham",
    price: 120000,
    originalPrice: 150000,
    unit: "hộp 500g",
    icon: "🐟",
    bg: "bg-red-50",
    tag: "Đặc sản",
    tagColor: "bg-red-500 text-white",
    rating: 4.7,
    reviews: 198,
    sold: 650,
    origin: "Làng nghề Hoằng Hóa",
    certifications: ["VSATTP", "Truyền thống"],
    desc: "Cá kho tộ theo công thức gia truyền làng nghề Hoằng Hóa, đậm đà hương vị, tiện dụng ăn liền.",
    specs: ["Nguyên liệu tươi sống", "Gia vị truyền thống", "Hộp kín chân không", "Hạn dùng 3 tháng"],
  },
];

export const banners = [
  {
    id: 1,
    title: "Giống lúa chịu mặn TH-M1",
    subtitle: "Độc quyền Viện Nông Nghiệp Thanh Hóa",
    desc: "Giải pháp cho vùng đất nhiễm mặn ven biển",
    cta: "Mua ngay",
    href: "/san-pham/lua-man",
    bg: "from-green-800 to-green-600",
    badge: "MỚI – ĐỘC QUYỀN",
  },
  {
    id: 2,
    title: "Cam Đường Canh Ngọc Lặc",
    subtitle: "Đặc sản Thanh Hóa – Vụ thu hoạch 2026",
    desc: "Tươi ngon từ vườn đến tay bạn",
    cta: "Đặt hàng ngay",
    href: "/san-pham/cam-duong",
    bg: "from-orange-700 to-amber-500",
    badge: "ĐANG VỤ MÙA",
  },
  {
    id: 3,
    title: "Phân hữu cơ vi sinh HUMIC",
    subtitle: "Cải thiện đất, tăng năng suất bền vững",
    desc: "Ưu đãi 15% cho đơn hàng trên 100kg",
    cta: "Xem ưu đãi",
    href: "/san-pham/phan-huu-co",
    bg: "from-emerald-800 to-teal-600",
    badge: "GIẢM 15%",
  },
];

export function formatPrice(price: number): string {
  return price.toLocaleString("vi-VN") + "đ";
}

export function discountPercent(original: number, current: number): number {
  return Math.round(((original - current) / original) * 100);
}
